- name: Get interface statistics
  become: true
  shell: "ovs-vsctl get interface {{ port }} statistics"
  register: if_stat

- debug:
    var: if_stat

- set_fact:
    if_stat: "{{if_stat.stdout[0:-1].split(',')}}"

- name: convert into dictionary
  set_fact:
    temp: "{{ temp | default({}) | combine({ stat[1:].split('=')[0] : stat[1:].split('=')[1]|int })}}"
  loop: "{{ if_stat }}"
  loop_control:
    loop_var: stat

- debug:
    var: temp

- name: update dictionary stats
  set_fact:
    stats: "{{ (stats | default({})) | combine({ port : temp})}}"
  when: if_stat is defined
